{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9d58c9d6-bacd-4e42-9930-ee5ac1a9469d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pickle\n",
    "import numpy as np\n",
    "\n",
    "# Load model\n",
    "with open(\"cardiovascular_disease_model.pkl\", \"rb\") as file:\n",
    "    model = pickle.load(file)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "27d1b42b-a7c0-44f7-a548-7555e3d47f65",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-01 18:25:29.949 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.385 \n",
      "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
      "  command:\n",
      "\n",
      "    streamlit run C:\\Users\\Dell\\AppData\\Local\\Programs\\Python\\Python312\\Lib\\site-packages\\ipykernel_launcher.py [ARGUMENTS]\n",
      "2025-05-01 18:25:30.385 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.386 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.388 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.389 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.391 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.392 Session state does not function when running a script without `streamlit run`\n",
      "2025-05-01 18:25:30.393 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.394 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.396 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.397 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.398 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.400 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.402 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.403 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.404 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.405 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.406 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.408 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.410 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.412 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.416 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.418 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.419 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.420 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.421 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.422 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.423 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.424 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.432 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.433 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.435 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.436 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.437 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.438 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.451 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.457 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.468 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.469 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.471 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.472 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.473 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.474 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.476 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.478 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.481 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.482 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.483 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.485 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.486 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.487 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.488 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.489 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.490 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.493 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.494 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:25:30.495 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "import streamlit as st\n",
    "\n",
    "st.title(\"💓 Heart Disease Risk Predictor\")\n",
    "\n",
    "# Numerical Inputs\n",
    "age = st.number_input(\"Age (years)\", min_value=1, max_value=120)\n",
    "resting_bp = st.number_input(\"Resting Blood Pressure (mm Hg)\", min_value=50, max_value=250)\n",
    "cholesterol = st.number_input(\"Serum Cholesterol (mg/dL)\", min_value=100, max_value=600)\n",
    "max_heart_rate = st.number_input(\"Maximum Heart Rate Achieved\", min_value=60, max_value=250)\n",
    "oldpeak = st.number_input(\"Oldpeak (ST depression induced by exercise)\", min_value=0.0, max_value=10.0, step=0.1)\n",
    "\n",
    "# Categorical Inputs with specified encodings\n",
    "\n",
    "# Sex: 1 = male, 0 = female\n",
    "sex = st.selectbox(\"Sex\", [\"Male\", \"Female\"])\n",
    "sex_val = 1 if sex == \"Male\" else 0\n",
    "\n",
    "# Chest Pain Type: 1 = typical angina, 2 = atypical angina, 3 = non-anginal pain, 4 = asymptomatic\n",
    "cp_options = {\n",
    "    \"Typical Angina\": 1,\n",
    "    \"Atypical Angina\": 2,\n",
    "    \"Non-anginal Pain\": 3,\n",
    "    \"Asymptomatic\": 4\n",
    "}\n",
    "chest_pain = st.selectbox(\"Chest Pain Type\", list(cp_options.keys()))\n",
    "cp_val = cp_options[chest_pain]\n",
    "\n",
    "# Fasting Blood Sugar: 1 = true (>120 mg/dL), 0 = false\n",
    "fbs = st.selectbox(\"Fasting Blood Sugar > 120 mg/dL\", [\"No\", \"Yes\"])\n",
    "fbs_val = 1 if fbs == \"Yes\" else 0\n",
    "\n",
    "# Resting ECG: 0 = normal, 1 = ST-T wave abnormality, 2 = left ventricular hypertrophy\n",
    "ecg_options = {\n",
    "    \"Normal\": 0,\n",
    "    \"ST-T Wave Abnormality\": 1,\n",
    "    \"Left Ventricular Hypertrophy\": 2\n",
    "}\n",
    "resting_ecg = st.selectbox(\"Resting ECG Results\", list(ecg_options.keys()))\n",
    "ecg_val = ecg_options[resting_ecg]\n",
    "\n",
    "# Exercise Induced Angina: 1 = yes, 0 = no\n",
    "ex_angina = st.selectbox(\"Exercise-Induced Angina\", [\"No\", \"Yes\"])\n",
    "exang_val = 1 if ex_angina == \"Yes\" else 0\n",
    "\n",
    "# Slope of ST Segment: 1 = upsloping, 2 = flat, 3 = downsloping\n",
    "slope_options = {\n",
    "    \"Upsloping\": 1,\n",
    "    \"Flat\": 2,\n",
    "    \"Downsloping\": 3\n",
    "}\n",
    "st_slope = st.selectbox(\"ST Segment Slope\", list(slope_options.keys()))\n",
    "slope_val = slope_options[st_slope]\n",
    "\n",
    "         \n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "899d64ee-2570-4d16-aa7a-fc35f20d2d8b",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-01 18:26:01.058 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:26:01.059 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:26:01.061 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:26:01.063 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-01 18:26:01.064 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    }
   ],
   "source": [
    "# Create input array\n",
    "input_data = [[\n",
    "    age, sex_val, cp_val, resting_bp, cholesterol, fbs_val,\n",
    "    ecg_val, max_heart_rate, exang_val, oldpeak, slope_val\n",
    "]]\n",
    "\n",
    "\n",
    "\n",
    "\n",
    "# Prediction\n",
    "if st.button(\"Predict\"):\n",
    "    prediction = model.predict(input_data)[0]\n",
    "    if prediction == 1:\n",
    "        st.error(\"⚠️ High Risk of Cardiovascular Disease\")\n",
    "    else:\n",
    "        st.success(\"✅ Low Risk of Cardiovascular Disease\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
